#
# Insteon Server
#
# http://github.com/tenstartups/insteon-server
#

FROM node:alpine

# Create app directory.
WORKDIR /usr/src/app

# Install app dependencies.
COPY Gruntfile.js .
COPY package.json .

# Install node application.
RUN npm install

# Install app source
COPY app.js .
ADD api api
ADD assets assets
ADD config config
ADD tasks tasks
ADD api api
ADD api api

EXPOSE 8080
CMD [ "npm", "start" ]
