#
# Insteon Server
#
# http://github.com/tenstartups/insteon-server
#

FROM resin/raspberrypi3-alpine-node:latest

# Create app directory.
WORKDIR /usr/src/app

# Install app dependencies.
COPY package.json .

# Install node application.
RUN npm install

# Install app source
COPY server.js .
ADD config ./config
ADD routes ./routes

EXPOSE 8080
CMD [ "npm", "start" ]
